### ISSUE TITLE
`toggle auto-test` in IntelliJ plugin 

### ISSUE THREAD

**Issue by oleksiyp** [kotest/kotest-intellij-plugin#21]
Hi,

using `kotlintest` and `IntelliJ Plugin` for it.

Have the following question: how to make `toggle auto-test` button work?
(highlighted by red zone on screenshot)

![image](https://user-images.githubusercontent.com/5249932/61746624-6b681f00-ad9c-11e9-82fa-cc0274aae8c9.png)

Thanks!

**Comment by sksamuel** [comment]
Moved issue to the plugin repo.

**Comment by StragaSevera** [comment]
What is the progress on this issue? It would be very handy to not manually run tests each time there is a change.

**Comment by georglundesgaard** [comment]
Has this feature request been abandoned?

I'm using IntelliJ IDEA Ultimate 2020.2 with kotest-intellij-plugin 1.1.16-IC-2020.1 and it does not work for me.

**Comment by sksamuel** [comment]
I'm on ultimate but I don't see this toggle auto test button.

![image](https://user-images.githubusercontent.com/743706/95682945-dd996f00-0bad-11eb-92cd-f0a22cb95e9c.png)

**Comment by christophsturm** [comment]
what idea version are you using? 
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1999/98964002-9681ff00-2508-11eb-8f79-0d66ed11f223.png">

**Comment by StragaSevera** [comment]
Is there any progress on this?

**Comment by enolive** [comment]
Tried it out today in Ultimate 2020.3.2. 

The auto-test button actually works on my machine, at least for maven and gradle projects. I don't think this is a bug in the plugin

For people who are struggling with it:

- Do you really run the tests with the Kotest Test runner (instead of say, gradle?)
- Did you activate Build Project automatically (Build, Execution, Deployment -> Compiler)? Without this setting, the auto test toggle will only work after building the project manually (Ctrl+F9 on Linux/Windows which I seldomly use)
